import { DomainResource } from './DomainResource'

export enum EventTimingEnum{
    AC = 'AC',
    ACD = 'ACD',
    ACM = 'ACM',
    ACV = 'ACV',
    AFT = 'AFT',
    AFT_EARLY = 'AFT.early',
    AFT_LATE = 'AFT.late',
    C = 'C',
    CD = 'CD',
    CM = 'CM',
    CV = 'CV',
    EVE = 'EVE',
    EVE_EARLY = 'EVE.early',
    EVE_LATE = 'EVE.late',
    HS = 'HS',
    MORN = 'MORN',
    MORN_EARLY = 'MORN.early',
    MORN_LATE = 'MORN.late',
    NIGHT = 'NIGHT',
    NOON = 'NOON',
    PC = 'PC',
    PCD = 'PCD',
    PCM = 'PCM',
    PCV = 'PCV',
    PHS = 'PHS',
    WAKE = 'WAKE',
}
